spring:
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: ${api.key.openai}
      embedding:
        enabled: false
      chat:
        enabled: false
        options:
          model: deepseek-chat
    zhipuai:
      chat:
        enabled: true
        options:
          model: glm-4-flash
      api-key: ${api.key.zhipuai}
    vectorstore:
      redis:
        initialize-schema: true
        index-name: custom-index
        prefix: custom-prefix
        batching-strategy: TOKEN_COUNT
  data:
    redis:
      url: redis://:${vector.redis.pwd}@${vector.redis.url}:${vector.redis.port}
